### PR TITLE
Make db view injectable by container

### PR DESCRIPTION
**Pull request by dducro**
Hey,

I came across this package and wanted to implement it into my project.
However DbView couldn't be resolved by the container because it has dependencies that have to be set by a setter in stead of by the constructor.
Therefor I made some changes so it can be used with auto injection and your not limited to the facade.
(I also formatted the classes)

### CODE REVIEW

**Comment by Flynsarmy** [comment]
Approve

**Comment by dducro** [comment]
Nice, thanks!

**Comment by Flynsarmy** [comment]
On holidays for a month. It'll be a while before I can look at this.

**Comment by dducro** [comment]
Ok, have fun on your holiday!
I'll use my fork in the mean time.

**Pull request merged**
