### PR TITLE
dont set DbView alias in service provider

### PR DESCRIPTION
**Pull request by AlexECP**
Was running into following error
```Non-static method Flynsarmy\DbBladeCompiler\DbView::make() should not be called statically```

Seems the advice of issue #30 + using dev-master instead of latest release fixes this

### CODE REVIEW

**Comment by AlexECP** [comment]
@Flynsarmy can you make a new release after this?  Thanks

**Comment by Flynsarmy** [comment]
What's the point of the loader line if you're no longer doing anything with it?

**Comment by Flynsarmy** [comment]
Does the alias still work now that you've removed all these lines? What version of Laravel are you on?

**Comment by AlexECP** [comment]
yes tested, as long as user follows instructions in readme and added the alias to `config/app.php`

**Pull request merged**
